version: '3.7'

services:
  webapi:
    build: .
    ports:
      - "8090:80"
    environment: # see https://github.com/dotnet/dotnet-docker/blob/main/samples/run-aspnetcore-https-development.md#linux
      ASPNETCORE_HTTP_PORT: 80
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: "http://+:80"
      REDIS_URL: "redis:6379"
    depends_on:
      - redis
  
  redis:
    image: docker.io/library/redis:7.2-alpine
    ports:
      - "6379:6379"
