// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using net_news_html.Library.Storage;

#nullable disable

namespace net_news_html.Migrations
{
    [DbContext(typeof(NewsDbContext))]
    [Migration("20250720012530_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("net_news_html.Models.PassKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PassKeys");
                });

            modelBuilder.Entity("net_news_html.Models.SavedNewsItem", b =>
                {
                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PassKeyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SaveDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Url");

                    b.HasIndex("PassKeyId");

                    b.ToTable("SavedNews");
                });

            modelBuilder.Entity("net_news_html.Models.SavedNewsItem", b =>
                {
                    b.HasOne("net_news_html.Models.PassKey", "PassKey")
                        .WithMany()
                        .HasForeignKey("PassKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PassKey");
                });
#pragma warning restore 612, 618
        }
    }
}
